name: Script integração para testes

on:
  schedule:
    - cron: '30 11 * * 5'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium PyPDF2

    - name: Run Python script
      run: python -m pytest

    if: github.ref == 'refs/heads/testes'
